export type MuscleGroup =
  | "chest"
  | "back"
  | "traps"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "quads"
  | "hamstrings"
  | "glutes"
  | "calves"
  | "core"
  | "forearms";

export type Equipment =
  | "barbell"
  | "dumbbell"
  | "machine"
  | "cable"
  | "bodyweight"
  | "kettlebell"
  | "band"
  | "smith";

export type ExerciseType = "compound" | "isolation";

// How weight is entered for this lift. Usually derived from `equipment`
// (see src/lib/loading.ts), but set explicitly when the default is wrong:
//  - "total"  the number you enter is the whole load (barbell, machine, cable)
//  - "each"   one dumbbell/kettlebell, held in each hand (default for those)
//  - "added"  bodyweight lift you can hang extra plates on (weighted pull-up, dip)
//  - "assist" machine that REMOVES weight; a bigger number is easier
//  - "none"   pure bodyweight, reps only, no weight field
export type WeightMode = "total" | "each" | "added" | "assist" | "none";

export interface Exercise {
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  secondary?: MuscleGroup[];
  equipment: Equipment;
  type: ExerciseType;
  /** override the equipment-derived weight-entry mode when it would be wrong */
  load?: WeightMode;
  alternatives: string[];
}

export const EXERCISES: Exercise[] = [
  // ─── CHEST (12) ───────────────────────────────────────────────────────────
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-bench-press",
      "smith-bench-press",
      "machine-chest-press",
      "cable-chest-press",
    ],
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-bench-press",
      "smith-bench-press",
      "machine-chest-press",
      "push-up",
    ],
  },
  {
    id: "smith-bench-press",
    name: "Smith Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-bench-press",
      "dumbbell-bench-press",
      "machine-chest-press",
    ],
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline Barbell Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "incline-dumbbell-bench-press",
      "incline-cable-fly",
      "smith-incline-bench-press",
    ],
  },
  {
    id: "incline-dumbbell-bench-press",
    name: "Incline Dumbbell Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "incline-barbell-bench-press",
      "incline-cable-fly",
      "smith-incline-bench-press",
    ],
  },
  {
    id: "smith-incline-bench-press",
    name: "Smith Incline Bench Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "incline-barbell-bench-press",
      "incline-dumbbell-bench-press",
      "incline-cable-fly",
    ],
  },
  {
    id: "cable-chest-press",
    name: "Cable Chest Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "barbell-bench-press",
      "dumbbell-bench-press",
      "machine-chest-press",
    ],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "barbell-bench-press",
      "dumbbell-bench-press",
      "cable-chest-press",
      "push-up",
    ],
  },
  {
    id: "push-up",
    name: "Push Up",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "bodyweight",
    type: "compound",
    alternatives: [
      "dumbbell-bench-press",
      "machine-chest-press",
      "cable-chest-press",
      "dumbbell-fly",
    ],
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Fly",
    muscleGroup: "chest",
    secondary: ["shoulders"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-fly",
      "machine-fly",
      "incline-cable-fly",
      "incline-dumbbell-fly",
    ],
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    muscleGroup: "chest",
    secondary: ["shoulders"],
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "dumbbell-fly",
      "machine-fly",
      "incline-cable-fly",
    ],
  },
  {
    id: "machine-fly",
    name: "Machine Fly",
    muscleGroup: "chest",
    secondary: ["shoulders"],
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "cable-fly",
      "dumbbell-fly",
      "incline-cable-fly",
    ],
  },
  {
    id: "incline-cable-fly",
    name: "Incline Cable Fly",
    muscleGroup: "chest",
    secondary: ["shoulders"],
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "incline-dumbbell-bench-press",
      "incline-barbell-bench-press",
      "dumbbell-fly",
      "cable-fly",
      "incline-dumbbell-fly",
    ],
  },

  // ─── BACK (14) ────────────────────────────────────────────────────────────
  {
    id: "barbell-deadlift",
    name: "Barbell Deadlift",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings", "core", "forearms"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "trap-bar-deadlift",
      "dumbbell-deadlift",
      "smith-deadlift",
      "cable-pull-through",
      "rack-pull",
    ],
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings", "quads"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "barbell-deadlift",
      "dumbbell-deadlift",
      "smith-deadlift",
      "sumo-deadlift",
    ],
  },
  {
    id: "dumbbell-deadlift",
    name: "Dumbbell Deadlift",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-deadlift",
      "trap-bar-deadlift",
      "kettlebell-deadlift",
    ],
  },
  {
    id: "smith-deadlift",
    name: "Smith Deadlift",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-deadlift",
      "dumbbell-deadlift",
      "trap-bar-deadlift",
    ],
  },
  {
    id: "barbell-bent-over-row",
    name: "Barbell Bent Over Row",
    muscleGroup: "back",
    secondary: ["biceps", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-row",
      "cable-seated-row",
      "machine-row",
      "t-bar-row",
    ],
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-bent-over-row",
      "cable-seated-row",
      "machine-row",
      "t-bar-row",
      "chest-supported-row",
    ],
  },
  {
    id: "cable-seated-row",
    name: "Cable Seated Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "barbell-bent-over-row",
      "dumbbell-row",
      "machine-row",
      "band-pull-apart",
    ],
  },
  {
    id: "machine-row",
    name: "Machine Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "cable-seated-row",
      "barbell-bent-over-row",
      "dumbbell-row",
      "chest-supported-row",
    ],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    muscleGroup: "back",
    secondary: ["biceps", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "barbell-bent-over-row",
      "dumbbell-row",
      "cable-seated-row",
    ],
  },
  {
    id: "pull-up",
    name: "Pull Up",
    muscleGroup: "back",
    secondary: ["biceps", "core"],
    equipment: "bodyweight",
    type: "compound",
    load: "added",
    alternatives: [
      "lat-pulldown",
      "assisted-pull-up",
      "cable-pull-down",
    ],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "pull-up",
      "machine-pulldown",
      "cable-pull-down",
    ],
  },
  {
    id: "machine-pulldown",
    name: "Lat Pulldown (Machine)",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "lat-pulldown",
      "pull-up",
      "cable-pull-down",
    ],
  },
  {
    id: "cable-pull-down",
    name: "Cable Pull Down",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "lat-pulldown",
      "machine-pulldown",
      "pull-up",
    ],
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull Up",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "machine",
    type: "compound",
    load: "assist",
    alternatives: [
      "pull-up",
      "lat-pulldown",
      "cable-pull-down",
    ],
  },
  {
    id: "assisted-chin-up",
    name: "Assisted Chin-Up",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "machine",
    type: "compound",
    load: "assist",
    alternatives: [
      "chin-up",
      "assisted-pull-up",
      "lat-pulldown",
    ],
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull Through",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "barbell-deadlift",
      "kettlebell-deadlift",
      "dumbbell-deadlift",
    ],
  },
  {
    id: "kettlebell-deadlift",
    name: "Kettlebell Deadlift",
    muscleGroup: "back",
    secondary: ["glutes", "hamstrings"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: [
      "barbell-deadlift",
      "dumbbell-deadlift",
      "cable-pull-through",
    ],
  },

  // ─── TRAPS (5) ────────────────────────────────────────────────────────────
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders", "forearms"],
    equipment: "barbell",
    type: "isolation",
    alternatives: ["dumbbell-shrug", "cable-shrug", "smith-shrug", "trap-bar-shrug", "machine-shrug"],
  },
  {
    id: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders", "forearms"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["barbell-shrug", "cable-shrug", "smith-shrug", "trap-bar-shrug"],
  },
  {
    id: "cable-shrug",
    name: "Cable Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders"],
    equipment: "cable",
    type: "isolation",
    alternatives: ["dumbbell-shrug", "barbell-shrug", "smith-shrug", "machine-shrug"],
  },
  {
    id: "smith-shrug",
    name: "Smith Machine Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders", "forearms"],
    equipment: "smith",
    type: "isolation",
    alternatives: ["barbell-shrug", "dumbbell-shrug", "cable-shrug"],
  },
  {
    id: "trap-bar-shrug",
    name: "Trap Bar Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders", "forearms"],
    equipment: "barbell",
    type: "isolation",
    alternatives: ["barbell-shrug", "dumbbell-shrug", "smith-shrug"],
  },

  // ─── SHOULDERS (12) ───────────────────────────────────────────────────────
  {
    id: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    muscleGroup: "shoulders",
    secondary: ["triceps", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-shoulder-press",
      "smith-overhead-press",
      "machine-shoulder-press",
      "cable-shoulder-press",
      "push-press",
    ],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    muscleGroup: "shoulders",
    secondary: ["triceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-overhead-press",
      "smith-overhead-press",
      "machine-shoulder-press",
    ],
  },
  {
    id: "smith-overhead-press",
    name: "Smith Overhead Press",
    muscleGroup: "shoulders",
    secondary: ["triceps"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-overhead-press",
      "dumbbell-shoulder-press",
      "machine-shoulder-press",
    ],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    muscleGroup: "shoulders",
    secondary: ["triceps"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "barbell-overhead-press",
      "dumbbell-shoulder-press",
      "cable-shoulder-press",
    ],
  },
  {
    id: "cable-shoulder-press",
    name: "Cable Shoulder Press",
    muscleGroup: "shoulders",
    secondary: ["triceps"],
    equipment: "cable",
    type: "compound",
    alternatives: [
      "barbell-overhead-press",
      "dumbbell-shoulder-press",
      "machine-shoulder-press",
    ],
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-lateral-raise",
      "machine-lateral-raise",
      "band-lateral-raise",
    ],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "dumbbell-lateral-raise",
      "machine-lateral-raise",
      "band-lateral-raise",
    ],
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "dumbbell-lateral-raise",
      "cable-lateral-raise",
      "band-lateral-raise",
    ],
  },
  {
    id: "band-lateral-raise",
    name: "Band Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "dumbbell-lateral-raise",
      "cable-lateral-raise",
      "machine-lateral-raise",
    ],
  },
  {
    id: "dumbbell-front-raise",
    name: "Dumbbell Front Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-front-raise",
      "barbell-front-raise",
      "dumbbell-lateral-raise",
    ],
  },
  {
    id: "cable-front-raise",
    name: "Cable Front Raise",
    muscleGroup: "shoulders",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "dumbbell-front-raise",
      "barbell-front-raise",
      "cable-lateral-raise",
    ],
  },
  {
    id: "barbell-front-raise",
    name: "Barbell Front Raise",
    muscleGroup: "shoulders",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "dumbbell-front-raise",
      "cable-front-raise",
      "dumbbell-lateral-raise",
    ],
  },
  {
    id: "dumbbell-rear-delt-fly",
    name: "Dumbbell Rear Delt Fly",
    muscleGroup: "shoulders",
    secondary: ["back"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-rear-delt-fly",
      "machine-rear-delt-fly",
      "band-pull-apart",
    ],
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    muscleGroup: "shoulders",
    secondary: ["back"],
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "dumbbell-rear-delt-fly",
      "machine-rear-delt-fly",
      "band-pull-apart",
    ],
  },
  {
    id: "machine-rear-delt-fly",
    name: "Machine Rear Delt Fly",
    muscleGroup: "shoulders",
    secondary: ["back"],
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "dumbbell-rear-delt-fly",
      "cable-rear-delt-fly",
      "band-pull-apart",
    ],
  },
  {
    id: "band-pull-apart",
    name: "Band Pull Apart",
    muscleGroup: "shoulders",
    secondary: ["back"],
    equipment: "band",
    type: "isolation",
    alternatives: [
      "dumbbell-rear-delt-fly",
      "cable-rear-delt-fly",
      "machine-rear-delt-fly",
    ],
  },

  // ─── BICEPS (8) ───────────────────────────────────────────────────────────
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "dumbbell-curl",
      "cable-curl",
      "machine-curl",
      "ez-bar-curl",
      "drag-curl",
    ],
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "barbell-curl",
      "cable-curl",
      "machine-curl",
      "hammer-curl",
    ],
  },
  {
    id: "ez-bar-curl",
    name: "EZ Bar Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "barbell-curl",
      "dumbbell-curl",
      "cable-curl",
    ],
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    muscleGroup: "biceps",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "barbell-curl",
      "dumbbell-curl",
      "machine-curl",
    ],
  },
  {
    id: "machine-curl",
    name: "Machine Curl",
    muscleGroup: "biceps",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "barbell-curl",
      "cable-curl",
      "dumbbell-curl",
    ],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: "biceps",
    secondary: ["forearms"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "dumbbell-curl",
      "cable-curl",
      "band-curl",
      "zottman-curl",
    ],
  },
  {
    id: "band-curl",
    name: "Band Curl",
    muscleGroup: "biceps",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "dumbbell-curl",
      "cable-curl",
      "machine-curl",
    ],
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "dumbbell-curl",
      "cable-curl",
      "barbell-curl",
    ],
  },

  // ─── TRICEPS (8) ──────────────────────────────────────────────────────────
  {
    id: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    muscleGroup: "triceps",
    secondary: ["chest", "shoulders"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dip",
      "skull-crusher",
      "cable-tricep-pushdown",
      "machine-tricep-press",
    ],
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    muscleGroup: "triceps",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "dumbbell-skull-crusher",
      "cable-overhead-tricep-extension",
      "cable-tricep-pushdown",
    ],
  },
  {
    id: "dumbbell-skull-crusher",
    name: "Dumbbell Skull Crusher",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "skull-crusher",
      "cable-overhead-tricep-extension",
      "cable-tricep-pushdown",
    ],
  },
  {
    id: "cable-tricep-pushdown",
    name: "Cable Tricep Pushdown",
    muscleGroup: "triceps",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "machine-tricep-press",
      "band-tricep-pushdown",
      "skull-crusher",
      "dip",
      "dumbbell-tricep-kickback",
    ],
  },
  {
    id: "cable-overhead-tricep-extension",
    name: "Cable Overhead Tricep Extension",
    muscleGroup: "triceps",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "dumbbell-overhead-tricep-extension",
      "skull-crusher",
      "cable-tricep-pushdown",
    ],
  },
  {
    id: "dumbbell-overhead-tricep-extension",
    name: "Dumbbell Overhead Tricep Extension",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-overhead-tricep-extension",
      "skull-crusher",
      "cable-tricep-pushdown",
    ],
  },
  {
    id: "dip",
    name: "Dip",
    muscleGroup: "triceps",
    secondary: ["chest", "shoulders"],
    equipment: "bodyweight",
    type: "compound",
    load: "added",
    alternatives: [
      "close-grip-bench-press",
      "cable-tricep-pushdown",
      "machine-tricep-press",
    ],
  },
  {
    id: "machine-tricep-press",
    name: "Machine Tricep Press",
    muscleGroup: "triceps",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "cable-tricep-pushdown",
      "dip",
      "close-grip-bench-press",
    ],
  },
  {
    id: "band-tricep-pushdown",
    name: "Band Tricep Pushdown",
    muscleGroup: "triceps",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "cable-tricep-pushdown",
      "machine-tricep-press",
      "dip",
    ],
  },

  // ─── QUADS (12) ───────────────────────────────────────────────────────────
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "barbell-front-squat",
      "smith-squat",
      "leg-press",
      "dumbbell-goblet-squat",
    ],
  },
  {
    id: "barbell-front-squat",
    name: "Barbell Front Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "barbell-back-squat",
      "smith-squat",
      "leg-press",
      "dumbbell-goblet-squat",
    ],
  },
  {
    id: "smith-squat",
    name: "Smith Squat",
    muscleGroup: "quads",
    secondary: ["glutes"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-back-squat",
      "barbell-front-squat",
      "leg-press",
      "hack-squat",
    ],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "barbell-back-squat",
      "smith-squat",
      "hack-squat",
      "dumbbell-goblet-squat",
      "single-leg-press",
    ],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    muscleGroup: "quads",
    secondary: ["glutes"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "barbell-back-squat",
      "leg-press",
      "smith-squat",
    ],
  },
  {
    id: "dumbbell-goblet-squat",
    name: "Dumbbell Goblet Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "core"],
    equipment: "dumbbell",
    type: "compound",
    load: "total", // one dumbbell held in both hands, not one per hand
    alternatives: [
      "barbell-back-squat",
      "leg-press",
      "kettlebell-goblet-squat",
      "smith-squat",
      "dumbbell-sumo-squat",
    ],
  },
  {
    id: "kettlebell-goblet-squat",
    name: "Kettlebell Goblet Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "core"],
    equipment: "kettlebell",
    type: "compound",
    load: "total", // one kettlebell held in both hands, not one per hand
    alternatives: [
      "dumbbell-goblet-squat",
      "barbell-back-squat",
      "leg-press",
      "kettlebell-front-squat",
    ],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "quads",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "cable-leg-extension",
      "band-leg-extension",
      "barbell-back-squat",
    ],
  },
  {
    id: "cable-leg-extension",
    name: "Cable Leg Extension",
    muscleGroup: "quads",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "leg-extension",
      "band-leg-extension",
    ],
  },
  {
    id: "band-leg-extension",
    name: "Band Leg Extension",
    muscleGroup: "quads",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "leg-extension",
      "cable-leg-extension",
    ],
  },
  {
    id: "barbell-lunge",
    name: "Barbell Lunge",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-lunge",
      "smith-lunge",
      "walking-lunge",
    ],
  },
  {
    id: "dumbbell-lunge",
    name: "Dumbbell Lunge",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-lunge",
      "smith-lunge",
      "walking-lunge",
    ],
  },
  {
    id: "smith-lunge",
    name: "Smith Lunge",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-lunge",
      "dumbbell-lunge",
      "walking-lunge",
    ],
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "bodyweight",
    type: "compound",
    load: "added", // hold a dumbbell in each hand to add load
    alternatives: [
      "dumbbell-lunge",
      "barbell-lunge",
      "smith-lunge",
    ],
  },

  // ─── HAMSTRINGS (8) ───────────────────────────────────────────────────────
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-romanian-deadlift",
      "smith-romanian-deadlift",
      "cable-pull-through",
      "leg-curl",
    ],
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "romanian-deadlift",
      "smith-romanian-deadlift",
      "leg-curl",
    ],
  },
  {
    id: "smith-romanian-deadlift",
    name: "Smith Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "romanian-deadlift",
      "dumbbell-romanian-deadlift",
      "leg-curl",
    ],
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscleGroup: "hamstrings",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "seated-leg-curl",
      "cable-leg-curl",
      "romanian-deadlift",
      "glute-ham-raise",
    ],
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    muscleGroup: "hamstrings",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "leg-curl",
      "cable-leg-curl",
      "dumbbell-romanian-deadlift",
    ],
  },
  {
    id: "cable-leg-curl",
    name: "Cable Leg Curl",
    muscleGroup: "hamstrings",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "leg-curl",
      "seated-leg-curl",
      "band-leg-curl",
    ],
  },
  {
    id: "band-leg-curl",
    name: "Band Leg Curl",
    muscleGroup: "hamstrings",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "cable-leg-curl",
      "leg-curl",
      "seated-leg-curl",
    ],
  },
  {
    id: "nordic-curl",
    name: "Nordic Curl",
    muscleGroup: "hamstrings",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "leg-curl",
      "seated-leg-curl",
      "cable-leg-curl",
      "glute-ham-raise",
    ],
  },

  // ─── GLUTES (8) ───────────────────────────────────────────────────────────
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "barbell",
    type: "compound",
    alternatives: [
      "dumbbell-hip-thrust",
      "smith-hip-thrust",
      "machine-hip-thrust",
      "glute-bridge",
    ],
  },
  {
    id: "dumbbell-hip-thrust",
    name: "Dumbbell Hip Thrust",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: [
      "barbell-hip-thrust",
      "smith-hip-thrust",
      "glute-bridge",
    ],
  },
  {
    id: "smith-hip-thrust",
    name: "Smith Hip Thrust",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "smith",
    type: "compound",
    alternatives: [
      "barbell-hip-thrust",
      "dumbbell-hip-thrust",
      "machine-hip-thrust",
    ],
  },
  {
    id: "machine-hip-thrust",
    name: "Machine Hip Thrust",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "machine",
    type: "compound",
    alternatives: [
      "barbell-hip-thrust",
      "smith-hip-thrust",
      "glute-bridge",
    ],
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "bodyweight",
    type: "compound",
    load: "added", // rest a dumbbell or plate on the hips to add load
    alternatives: [
      "barbell-hip-thrust",
      "dumbbell-hip-thrust",
      "cable-kickback",
    ],
  },
  {
    id: "cable-kickback",
    name: "Cable Kickback",
    muscleGroup: "glutes",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "machine-kickback",
      "band-kickback",
      "glute-bridge",
    ],
  },
  {
    id: "machine-kickback",
    name: "Machine Kickback",
    muscleGroup: "glutes",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "cable-kickback",
      "band-kickback",
      "barbell-hip-thrust",
    ],
  },
  {
    id: "band-kickback",
    name: "Band Kickback",
    muscleGroup: "glutes",
    equipment: "band",
    type: "isolation",
    alternatives: [
      "cable-kickback",
      "machine-kickback",
      "glute-bridge",
    ],
  },

  // ─── CALVES (5) ───────────────────────────────────────────────────────────
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    muscleGroup: "calves",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "seated-calf-raise",
      "dumbbell-calf-raise",
      "barbell-calf-raise",
      "bodyweight-calf-raise",
      "donkey-calf-raise",
    ],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    muscleGroup: "calves",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "standing-calf-raise",
      "dumbbell-calf-raise",
      "bodyweight-calf-raise",
    ],
  },
  {
    id: "dumbbell-calf-raise",
    name: "Dumbbell Calf Raise",
    muscleGroup: "calves",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "standing-calf-raise",
      "seated-calf-raise",
      "barbell-calf-raise",
      "bodyweight-calf-raise",
    ],
  },
  {
    id: "barbell-calf-raise",
    name: "Barbell Calf Raise",
    muscleGroup: "calves",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "standing-calf-raise",
      "dumbbell-calf-raise",
      "bodyweight-calf-raise",
    ],
  },
  {
    id: "bodyweight-calf-raise",
    name: "Bodyweight Calf Raise",
    muscleGroup: "calves",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "standing-calf-raise",
      "seated-calf-raise",
      "dumbbell-calf-raise",
    ],
  },

  // ─── CORE (12) ────────────────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "cable-plank",
      "ab-wheel-rollout",
      "hollow-body-hold",
    ],
  },
  {
    id: "cable-plank",
    name: "Cable Plank",
    muscleGroup: "core",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "plank",
      "ab-wheel-rollout",
      "hollow-body-hold",
    ],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "plank",
      "cable-crunch",
      "hollow-body-hold",
    ],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    muscleGroup: "core",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "machine-crunch",
      "crunch",
      "decline-crunch",
    ],
  },
  {
    id: "machine-crunch",
    name: "Machine Crunch",
    muscleGroup: "core",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "cable-crunch",
      "crunch",
      "decline-crunch",
    ],
  },
  {
    id: "crunch",
    name: "Crunch",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "cable-crunch",
      "machine-crunch",
      "decline-crunch",
    ],
  },
  {
    id: "decline-crunch",
    name: "Decline Crunch",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "crunch",
      "cable-crunch",
      "machine-crunch",
    ],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "captain-chair-leg-raise",
      "cable-leg-raise",
      "lying-leg-raise",
    ],
  },
  {
    id: "captain-chair-leg-raise",
    name: "Captain Chair Leg Raise",
    muscleGroup: "core",
    equipment: "machine",
    type: "isolation",
    alternatives: [
      "hanging-leg-raise",
      "cable-leg-raise",
      "lying-leg-raise",
    ],
  },
  {
    id: "cable-leg-raise",
    name: "Cable Leg Raise",
    muscleGroup: "core",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "hanging-leg-raise",
      "captain-chair-leg-raise",
      "lying-leg-raise",
    ],
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "hanging-leg-raise",
      "side-lying-leg-raise",
      "cable-leg-raise",
      "reverse-crunch",
    ],
  },
  {
    id: "side-lying-leg-raise",
    name: "Side-Lying Leg Raise",
    muscleGroup: "core",
    secondary: ["glutes"],
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "lying-leg-raise",
      "side-plank",
      "hip-abduction-machine",
    ],
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: [
      "plank",
      "ab-wheel-rollout",
      "crunch",
      "dead-bug",
    ],
  },
  {
    id: "cable-woodchop",
    name: "Cable Woodchop",
    muscleGroup: "core",
    secondary: ["shoulders"],
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "band-woodchop",
      "dumbbell-side-bend",
      "cable-crunch",
      "pallof-press",
    ],
  },
  {
    id: "band-woodchop",
    name: "Band Woodchop",
    muscleGroup: "core",
    secondary: ["shoulders"],
    equipment: "band",
    type: "isolation",
    alternatives: [
      "cable-woodchop",
      "dumbbell-side-bend",
      "cable-crunch",
    ],
  },
  {
    id: "dumbbell-side-bend",
    name: "Dumbbell Side Bend",
    muscleGroup: "core",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "cable-woodchop",
      "band-woodchop",
      "crunch",
    ],
  },

  // ─── FOREARMS (5) ─────────────────────────────────────────────────────────
  {
    id: "barbell-wrist-curl",
    name: "Barbell Wrist Curl",
    muscleGroup: "forearms",
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "dumbbell-wrist-curl",
      "cable-wrist-curl",
      "reverse-barbell-curl",
      "wrist-roller",
      "behind-the-back-wrist-curl",
    ],
  },
  {
    id: "dumbbell-wrist-curl",
    name: "Dumbbell Wrist Curl",
    muscleGroup: "forearms",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "barbell-wrist-curl",
      "cable-wrist-curl",
      "reverse-dumbbell-curl",
    ],
  },
  {
    id: "cable-wrist-curl",
    name: "Cable Wrist Curl",
    muscleGroup: "forearms",
    equipment: "cable",
    type: "isolation",
    alternatives: [
      "barbell-wrist-curl",
      "dumbbell-wrist-curl",
      "reverse-barbell-curl",
    ],
  },
  {
    id: "reverse-barbell-curl",
    name: "Reverse Barbell Curl",
    muscleGroup: "forearms",
    secondary: ["biceps"],
    equipment: "barbell",
    type: "isolation",
    alternatives: [
      "reverse-dumbbell-curl",
      "barbell-wrist-curl",
      "cable-wrist-curl",
    ],
  },
  {
    id: "reverse-dumbbell-curl",
    name: "Reverse Dumbbell Curl",
    muscleGroup: "forearms",
    secondary: ["biceps"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: [
      "reverse-barbell-curl",
      "dumbbell-wrist-curl",
      "cable-wrist-curl",
      "zottman-curl",
    ],
  },

  // ─── ADDED: extra variety across every group ──────────────────────────────
  // Chest
  {
    id: "decline-barbell-bench-press",
    name: "Decline Barbell Bench Press",
    muscleGroup: "chest",
    secondary: ["triceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["barbell-bench-press", "dumbbell-bench-press", "machine-chest-press"],
  },
  {
    id: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    muscleGroup: "chest",
    secondary: ["back"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["dumbbell-fly", "cable-fly", "straight-arm-pulldown"],
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    muscleGroup: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["incline-barbell-bench-press", "machine-chest-press", "dumbbell-shoulder-press"],
  },
  // Back
  {
    id: "pendlay-row",
    name: "Pendlay Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["barbell-bent-over-row", "t-bar-row", "dumbbell-row"],
  },
  {
    id: "chin-up",
    name: "Chin-Up",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "bodyweight",
    type: "compound",
    load: "added",
    alternatives: ["pull-up", "assisted-chin-up", "lat-pulldown", "assisted-pull-up"],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "bodyweight",
    type: "compound",
    alternatives: ["dumbbell-row", "machine-row", "cable-seated-row"],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    muscleGroup: "back",
    equipment: "cable",
    type: "isolation",
    alternatives: ["lat-pulldown", "cable-pull-down", "dumbbell-pullover"],
  },
  {
    id: "kettlebell-row",
    name: "Kettlebell Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["dumbbell-row", "machine-row", "t-bar-row"],
  },
  // Shoulders
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscleGroup: "shoulders",
    secondary: ["triceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["dumbbell-shoulder-press", "machine-shoulder-press", "barbell-overhead-press", "kettlebell-press"],
  },
  {
    id: "barbell-upright-row",
    name: "Barbell Upright Row",
    muscleGroup: "shoulders",
    secondary: ["biceps"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["cable-upright-row", "dumbbell-lateral-raise", "barbell-overhead-press", "kettlebell-sumo-high-pull"],
  },
  {
    id: "cable-upright-row",
    name: "Cable Upright Row",
    muscleGroup: "shoulders",
    secondary: ["biceps"],
    equipment: "cable",
    type: "compound",
    alternatives: ["barbell-upright-row", "cable-lateral-raise", "machine-shoulder-press"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscleGroup: "shoulders",
    secondary: ["back"],
    equipment: "cable",
    type: "isolation",
    alternatives: ["cable-rear-delt-fly", "machine-rear-delt-fly", "band-pull-apart"],
  },
  // Biceps
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    type: "isolation",
    alternatives: ["machine-preacher-curl", "ez-bar-curl", "barbell-curl"],
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    muscleGroup: "biceps",
    equipment: "machine",
    type: "isolation",
    alternatives: ["preacher-curl", "machine-curl", "cable-curl"],
  },
  {
    id: "dumbbell-concentration-curl",
    name: "Concentration Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["dumbbell-curl", "incline-dumbbell-curl", "cable-curl"],
  },
  {
    id: "dumbbell-spider-curl",
    name: "Spider Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["preacher-curl", "incline-dumbbell-curl", "cable-curl"],
  },
  {
    id: "cable-rope-hammer-curl",
    name: "Cable Rope Hammer Curl",
    muscleGroup: "biceps",
    secondary: ["forearms"],
    equipment: "cable",
    type: "isolation",
    alternatives: ["hammer-curl", "cable-curl", "dumbbell-curl"],
  },
  // Triceps
  {
    id: "bench-dip",
    name: "Bench Dip",
    muscleGroup: "triceps",
    equipment: "bodyweight",
    type: "compound",
    alternatives: ["dip", "diamond-push-up", "cable-tricep-pushdown"],
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-Up",
    muscleGroup: "triceps",
    secondary: ["chest"],
    equipment: "bodyweight",
    type: "compound",
    alternatives: ["push-up", "bench-dip", "close-grip-bench-press"],
  },
  {
    id: "kettlebell-overhead-tricep-extension",
    name: "Kettlebell Overhead Extension",
    muscleGroup: "triceps",
    equipment: "kettlebell",
    type: "isolation",
    alternatives: ["dumbbell-overhead-tricep-extension", "cable-overhead-tricep-extension", "skull-crusher"],
  },
  // Quads
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["dumbbell-lunge", "walking-lunge", "smith-bulgarian-split-squat"],
  },
  {
    id: "smith-bulgarian-split-squat",
    name: "Smith Bulgarian Split Squat",
    muscleGroup: "quads",
    secondary: ["glutes"],
    equipment: "smith",
    type: "compound",
    alternatives: ["bulgarian-split-squat", "smith-lunge", "smith-squat"],
  },
  {
    id: "dumbbell-step-up",
    name: "Dumbbell Step-Up",
    muscleGroup: "quads",
    secondary: ["glutes"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["dumbbell-lunge", "bulgarian-split-squat", "walking-lunge", "box-jump"],
  },
  {
    id: "sissy-squat",
    name: "Sissy Squat",
    muscleGroup: "quads",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["leg-extension", "hack-squat", "dumbbell-goblet-squat"],
  },
  // Hamstrings
  {
    id: "barbell-good-morning",
    name: "Good Morning",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["romanian-deadlift", "dumbbell-romanian-deadlift", "nordic-curl", "back-extension"],
  },
  {
    id: "single-leg-dumbbell-rdl",
    name: "Single-Leg Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondary: ["glutes"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["dumbbell-romanian-deadlift", "romanian-deadlift", "leg-curl"],
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "core"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["kettlebell-deadlift", "romanian-deadlift", "barbell-hip-thrust", "kettlebell-clean"],
  },
  // Glutes
  {
    id: "hip-abduction-machine",
    name: "Hip Abduction Machine",
    muscleGroup: "glutes",
    equipment: "machine",
    type: "isolation",
    alternatives: ["cable-glute-kickback", "glute-bridge", "machine-hip-thrust", "monster-walk"],
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    muscleGroup: "glutes",
    equipment: "cable",
    type: "isolation",
    alternatives: ["hip-abduction-machine", "single-leg-glute-bridge", "cable-pull-through"],
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    muscleGroup: "glutes",
    secondary: ["hamstrings"],
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["glute-bridge", "barbell-hip-thrust", "cable-glute-kickback"],
  },
  // Calves
  {
    id: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    muscleGroup: "calves",
    equipment: "machine",
    type: "isolation",
    alternatives: ["standing-calf-raise", "seated-calf-raise", "smith-calf-raise"],
  },
  {
    id: "smith-calf-raise",
    name: "Smith Calf Raise",
    muscleGroup: "calves",
    equipment: "smith",
    type: "isolation",
    alternatives: ["standing-calf-raise", "barbell-calf-raise", "leg-press-calf-raise"],
  },
  {
    id: "single-leg-dumbbell-calf-raise",
    name: "Single-Leg Calf Raise",
    muscleGroup: "calves",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["dumbbell-calf-raise", "bodyweight-calf-raise", "standing-calf-raise"],
  },
  // Core
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["cable-woodchop", "bicycle-crunch", "dumbbell-side-bend", "landmine-rotation"],
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["crunch", "russian-twist", "hanging-leg-raise", "mountain-climber"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["plank", "dumbbell-side-bend", "hollow-body-hold", "copenhagen-plank"],
  },
  // Forearms
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    muscleGroup: "forearms",
    secondary: ["core"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["dumbbell-wrist-curl", "plate-pinch", "barbell-wrist-curl", "dead-hang"],
  },
  {
    id: "plate-pinch",
    name: "Plate Pinch",
    muscleGroup: "forearms",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["farmers-carry", "barbell-wrist-curl", "dumbbell-wrist-curl"],
  },
  {
    id: "dumbbell-reverse-wrist-curl",
    name: "Dumbbell Reverse Wrist Curl",
    muscleGroup: "forearms",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["dumbbell-wrist-curl", "barbell-wrist-curl", "reverse-dumbbell-curl"],
  },

  // ─── ADDED: thin groups, missing gym stations, kettlebell work ────────────
  // Traps
  {
    id: "machine-shrug",
    name: "Machine Shrug",
    muscleGroup: "traps",
    secondary: ["shoulders", "forearms"],
    equipment: "machine",
    type: "isolation",
    alternatives: ["barbell-shrug", "dumbbell-shrug", "cable-shrug", "smith-shrug"],
  },
  {
    id: "barbell-behind-the-back-shrug",
    name: "Behind-the-Back Barbell Shrug",
    muscleGroup: "traps",
    secondary: ["forearms"],
    equipment: "barbell",
    type: "isolation",
    alternatives: ["barbell-shrug", "smith-shrug", "machine-shrug", "dumbbell-shrug"],
  },
  {
    id: "kettlebell-sumo-high-pull",
    name: "Kettlebell Sumo High Pull",
    muscleGroup: "traps",
    secondary: ["shoulders", "glutes", "hamstrings"],
    equipment: "kettlebell",
    type: "compound",
    load: "total", // one kettlebell held in both hands
    alternatives: ["barbell-upright-row", "cable-upright-row", "kettlebell-swing", "dumbbell-shrug"],
  },
  // Calves
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    muscleGroup: "calves",
    equipment: "machine",
    type: "isolation",
    alternatives: ["standing-calf-raise", "leg-press-calf-raise", "seated-calf-raise", "smith-calf-raise"],
  },
  {
    id: "tibialis-raise",
    name: "Tibialis Raise",
    muscleGroup: "calves", // nearest enum bucket; it's the shin (dorsiflexor)
    equipment: "bodyweight",
    type: "isolation",
    // no honest same-movement swap in the library: calf raises are the antagonist
    alternatives: [],
  },
  // Forearms
  {
    id: "wrist-roller",
    name: "Wrist Roller",
    muscleGroup: "forearms",
    equipment: "bodyweight",
    type: "isolation",
    load: "total", // the plate hung from the roller is the whole load
    alternatives: ["barbell-wrist-curl", "dumbbell-wrist-curl", "dumbbell-reverse-wrist-curl", "farmers-carry"],
  },
  {
    id: "behind-the-back-wrist-curl",
    name: "Behind-the-Back Wrist Curl",
    muscleGroup: "forearms",
    equipment: "barbell",
    type: "isolation",
    alternatives: ["barbell-wrist-curl", "dumbbell-wrist-curl", "cable-wrist-curl"],
  },
  {
    id: "dead-hang",
    name: "Dead Hang",
    muscleGroup: "forearms",
    secondary: ["back", "shoulders"],
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["farmers-carry", "plate-pinch", "wrist-roller"],
  },
  {
    id: "zottman-curl",
    name: "Zottman Curl",
    muscleGroup: "biceps",
    secondary: ["forearms"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["reverse-dumbbell-curl", "hammer-curl", "reverse-barbell-curl", "dumbbell-wrist-curl"],
  },
  // Hamstrings
  {
    id: "glute-ham-raise",
    name: "Glute-Ham Raise",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "machine",
    type: "isolation",
    load: "added", // bodyweight on the GHD; hold a plate to add load
    alternatives: ["nordic-curl", "leg-curl", "seated-leg-curl", "romanian-deadlift"],
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    muscleGroup: "glutes",
    secondary: ["quads", "hamstrings", "back"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["barbell-deadlift", "romanian-deadlift", "trap-bar-deadlift", "rack-pull"],
  },
  {
    id: "kettlebell-clean",
    name: "Kettlebell Clean",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "shoulders", "forearms"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["kettlebell-swing", "kettlebell-deadlift", "dumbbell-romanian-deadlift"],
  },
  // Glutes
  {
    id: "hip-adduction-machine",
    name: "Hip Adduction Machine",
    muscleGroup: "glutes",
    equipment: "machine",
    type: "isolation",
    alternatives: ["dumbbell-sumo-squat", "copenhagen-plank", "barbell-back-squat"],
  },
  {
    id: "reverse-hyperextension",
    name: "Reverse Hyperextension",
    muscleGroup: "glutes",
    secondary: ["hamstrings", "back"],
    equipment: "machine",
    type: "isolation",
    alternatives: ["back-extension", "barbell-hip-thrust", "glute-bridge", "machine-kickback"],
  },
  {
    id: "dumbbell-sumo-squat",
    name: "Dumbbell Sumo Squat",
    muscleGroup: "glutes",
    secondary: ["quads", "hamstrings"],
    equipment: "dumbbell",
    type: "compound",
    load: "total", // one dumbbell held in both hands, not one per hand
    alternatives: ["dumbbell-goblet-squat", "kettlebell-goblet-squat", "hip-adduction-machine", "barbell-back-squat"],
  },
  {
    id: "monster-walk",
    name: "Monster Walk",
    muscleGroup: "glutes",
    equipment: "band",
    type: "isolation",
    load: "none", // band tension only — nothing to enter
    alternatives: ["hip-abduction-machine", "band-kickback", "side-lying-leg-raise", "cable-glute-kickback"],
  },
  // Back
  {
    id: "rack-pull",
    name: "Rack Pull",
    muscleGroup: "back",
    secondary: ["traps", "glutes", "forearms"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["barbell-deadlift", "trap-bar-deadlift", "smith-deadlift", "barbell-shrug"],
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Dumbbell Row",
    muscleGroup: "back",
    secondary: ["biceps"],
    equipment: "dumbbell",
    type: "compound",
    alternatives: ["machine-row", "dumbbell-row", "t-bar-row", "cable-seated-row"],
  },
  {
    id: "back-extension",
    name: "Back Extension",
    muscleGroup: "glutes",
    secondary: ["hamstrings", "back"],
    equipment: "machine",
    type: "isolation",
    load: "added", // bodyweight on the 45° bench; hug a plate to add load
    alternatives: ["reverse-hyperextension", "romanian-deadlift", "glute-bridge", "barbell-good-morning"],
  },
  // Shoulders
  {
    id: "kettlebell-press",
    name: "Kettlebell Press",
    muscleGroup: "shoulders",
    secondary: ["triceps", "core"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["dumbbell-shoulder-press", "barbell-overhead-press", "arnold-press", "push-press"],
  },
  {
    id: "kettlebell-snatch",
    name: "Kettlebell Snatch",
    muscleGroup: "hamstrings",
    secondary: ["glutes", "shoulders", "core"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["kettlebell-press", "kettlebell-swing", "kettlebell-clean", "push-press"],
  },
  {
    id: "push-press",
    name: "Push Press",
    muscleGroup: "shoulders",
    secondary: ["triceps", "quads", "core"],
    equipment: "barbell",
    type: "compound",
    alternatives: ["barbell-overhead-press", "dumbbell-shoulder-press", "smith-overhead-press", "kettlebell-press"],
  },
  // Biceps
  {
    id: "drag-curl",
    name: "Drag Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    type: "isolation",
    alternatives: ["barbell-curl", "ez-bar-curl", "dumbbell-curl", "dumbbell-spider-curl"],
  },
  // Triceps
  {
    id: "dumbbell-tricep-kickback",
    name: "Dumbbell Tricep Kickback",
    muscleGroup: "triceps",
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["cable-tricep-pushdown", "dumbbell-overhead-tricep-extension", "band-tricep-pushdown"],
  },
  // Quads
  {
    id: "single-leg-press",
    name: "Single-Leg Press",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: "machine",
    type: "compound",
    alternatives: ["leg-press", "bulgarian-split-squat", "dumbbell-step-up", "hack-squat"],
  },
  {
    id: "box-jump",
    name: "Box Jump",
    muscleGroup: "quads",
    secondary: ["glutes", "hamstrings", "calves"],
    equipment: "bodyweight",
    type: "compound",
    alternatives: ["dumbbell-step-up", "walking-lunge", "dumbbell-goblet-squat"],
  },
  {
    id: "sled-push",
    name: "Sled Push",
    muscleGroup: "quads",
    secondary: ["glutes", "calves", "core"],
    equipment: "machine",
    type: "compound",
    alternatives: ["leg-press", "walking-lunge", "hack-squat", "dumbbell-step-up"],
  },
  {
    id: "kettlebell-front-squat",
    name: "Kettlebell Front Squat",
    muscleGroup: "quads",
    secondary: ["glutes", "core"],
    equipment: "kettlebell",
    type: "compound",
    alternatives: ["kettlebell-goblet-squat", "barbell-front-squat", "dumbbell-goblet-squat", "barbell-back-squat"],
  },
  // Chest
  {
    id: "incline-dumbbell-fly",
    name: "Incline Dumbbell Fly",
    muscleGroup: "chest",
    secondary: ["shoulders"],
    equipment: "dumbbell",
    type: "isolation",
    alternatives: ["incline-cable-fly", "dumbbell-fly", "cable-fly", "machine-fly"],
  },
  // Core
  {
    id: "pallof-press",
    name: "Pallof Press",
    muscleGroup: "core",
    equipment: "cable",
    type: "isolation",
    alternatives: ["cable-woodchop", "band-woodchop", "cable-plank", "side-plank"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["hollow-body-hold", "plank", "lying-leg-raise", "bicycle-crunch"],
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscleGroup: "core",
    secondary: ["quads", "shoulders"],
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["plank", "bicycle-crunch", "hanging-leg-raise"],
  },
  {
    id: "turkish-get-up",
    name: "Turkish Get-Up",
    muscleGroup: "core",
    secondary: ["shoulders", "glutes"],
    equipment: "kettlebell",
    type: "compound",
    load: "total", // one bell for the whole movement, not one per hand
    alternatives: ["kettlebell-windmill", "side-plank", "dumbbell-side-bend", "hollow-body-hold"],
  },
  {
    id: "kettlebell-windmill",
    name: "Kettlebell Windmill",
    muscleGroup: "core",
    secondary: ["shoulders", "hamstrings"],
    equipment: "kettlebell",
    type: "isolation",
    alternatives: ["turkish-get-up", "dumbbell-side-bend", "russian-twist", "side-plank"],
  },
  {
    id: "landmine-rotation",
    name: "Landmine Rotation",
    muscleGroup: "core",
    secondary: ["shoulders"],
    equipment: "barbell",
    type: "isolation",
    alternatives: ["cable-woodchop", "band-woodchop", "russian-twist", "pallof-press"],
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["lying-leg-raise", "hanging-leg-raise", "crunch", "cable-crunch"],
  },
  // "Adductor Hold" naming keeps the demo matcher from pairing this side-lying
  // adductor plank with a plain front-plank photo (wrong movement).
  {
    id: "copenhagen-plank",
    name: "Copenhagen Adductor Hold",
    muscleGroup: "core",
    secondary: ["glutes"],
    equipment: "bodyweight",
    type: "isolation",
    alternatives: ["side-plank", "side-lying-leg-raise", "hip-adduction-machine", "plank"],
  },
];

export const EXERCISES_BY_ID: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);
